global:
  scrape_interval: 7s  # How often Prometheus will scrape metrics

scrape_configs:
  - job_name: 'graphql-server'
    static_configs:
      - targets: ['localhost:3001']  # The GraphQL server exposing metrics
